server:
  port: 8080

spring:
  application:
    name: log-ingestor
  threads:
    virtual:
      enabled: true
  kafka:
    enabled: true
    bootstrap-servers: ${KAFKA_SERVERS:kafka:29092}
    producer:
      batch-size: 32768
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 10
      compression-type: "snappy"
    admin:
      properties:
        # On donne plus de temps Ã  l'AdminClient pour trouver Kafka au boot
        request.timeout.ms: 20000
        retry.backoff.ms: 500
    properties:
      acks: all
      retries: 10
      retry.backoff.ms: 1000
grpc:
  server:
    port: 50051
    address: 0.0.0.0

app:
  kafka:
    topic-name: "app-logs"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true
    kafka:
      enabled: true